name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8' 
      - run: pip install pipenv black codespell ruff
      - run: pipenv install --dev
      - run: python -m black .
      - run: python -m codespell . --ignore-words-list=asend,gae --skip=./.*
      - run: python -m ruff .
