name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
      - run: pip install pipenv
      - run: pipenv install --dev
      - run: black .
      - run: codespell . --ignore-words-list=asend,gae --skip=./.*
      - run: ruff .
